name: flutter_quick_paste
description: 快速粘贴工具 - 快捷键弹出预置文本列表，双击自动粘贴
publish_to: 'none'
version: 0.2.2

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: 6.1.5+1
  shared_preferences: 2.5.5
  path_provider: 2.1.5
  path: 1.9.1
  window_manager: 0.5.1
  hotkey_manager: 0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
